LANGUAGES: list[dict[str, str]] = [
    {"code": "auto", "name": "Auto-detect", "nativeName": "Auto"},
    {"code": "en", "name": "English", "nativeName": "English"},
    {"code": "vi", "name": "Vietnamese", "nativeName": "Tiếng Việt"},
    {"code": "zh", "name": "Chinese", "nativeName": "中文"},
    {"code": "ja", "name": "Japanese", "nativeName": "日本語"},
    {"code": "ko", "name": "Korean", "nativeName": "한국어"},
    {"code": "fr", "name": "French", "nativeName": "Français"},
    {"code": "de", "name": "German", "nativeName": "Deutsch"},
    {"code": "es", "name": "Spanish", "nativeName": "Español"},
    {"code": "pt", "name": "Portuguese", "nativeName": "Português"},
    {"code": "ru", "name": "Russian", "nativeName": "Русский"},
    {"code": "it", "name": "Italian", "nativeName": "Italiano"},
    {"code": "th", "name": "Thai", "nativeName": "ไทย"},
    {"code": "id", "name": "Indonesian", "nativeName": "Bahasa Indonesia"},
    {"code": "ar", "name": "Arabic", "nativeName": "العربية"},
    {"code": "hi", "name": "Hindi", "nativeName": "हिन्दी"},
    {"code": "tr", "name": "Turkish", "nativeName": "Türkçe"},
    {"code": "nl", "name": "Dutch", "nativeName": "Nederlands"},
    {"code": "pl", "name": "Polish", "nativeName": "Polski"},
    {"code": "uk", "name": "Ukrainian", "nativeName": "Українська"},
]
